import { mdiAccount, mdiAccountMinus, mdiAccountPlus, mdiAccountVoice, mdiAlert, mdiApplicationVariable, mdiArchive, mdiArchiveEdit, mdiArchivePlus, mdiArrowExpandDown, mdiArrowExpandHorizontal, mdiArrowExpandUp, mdiArrowExpandVertical, mdiArrowRightBox, mdiArrowULeftTop, mdiBookMultipleOutline, mdiBookOpenVariantOutline, mdiCheckboxBlankOutline, mdiCheckboxMarked, mdiCheckCircle, mdiChevronDown, mdiChevronRight, mdiClose, mdiCloseCircleOutline, mdiCog, mdiCreation, mdiDice3, mdiDiceMultiple, mdiDotsCircle, mdiDotsHorizontal, mdiEmoticon, mdiEqual, mdiFlag, mdiFormatHorizontalAlignCenter, mdiFormatHorizontalAlignLeft, mdiFormatHorizontalAlignRight, mdiFormatLetterCaseLower, mdiFormatLetterCaseUpper, mdiFormatListCheckbox, mdiFormatListChecks, mdiFormatListGroup, mdiFormatListText, mdiFormatText, mdiFormTextbox, mdiGreaterThan, mdiGreaterThanOrEqual, mdiHome, mdiImageArea, mdiLessThan, mdiLessThanOrEqual, mdiMapSearch, mdiMenuDown, mdiMinus, mdiMusic, mdiNotEqualVariant, mdiPause, mdiPercent, mdiPlay, mdiPlus, mdiPlusBox, mdiPound, mdiPoundBox, mdiRestart, mdiScriptText, mdiScriptTextPlay, mdiSignatureText, mdiSlashForward, mdiSourceBranch, mdiSquareOutline, mdiText, mdiTextBoxOutline, mdiTrashCan, mdiUpload, mdiVariable, mdiVolumeHigh } from '@mdi/js'

import type { ExprPrimitiveValueType, ExprType } from '../../types/expressions'
import type { StepType } from '../../types/steps'
import type { ProjectEditorTab } from '../../types/viewstate'

export const COMMON_ICONS = {
    success: mdiCheckCircle,
    warning: mdiAlert,
    newProject: mdiArchivePlus,
    openProject: mdiArchiveEdit,
    cancel: mdiClose,
    close: mdiCloseCircleOutline,
    checkboxChecked: mdiCheckboxMarked,
    checkboxUnchecked: mdiCheckboxBlankOutline,
    addItem: mdiPlusBox,
    deleteItem: mdiTrashCan,
    breadcrumbArrow: mdiChevronRight,
    dropdownArrow: mdiChevronDown,
    alignLeft: mdiFormatHorizontalAlignLeft,
    alignRight: mdiFormatHorizontalAlignRight,
    alignCenter: mdiFormatHorizontalAlignCenter,
    alignAuto: mdiCreation,
    alignCustom: mdiPercent,
    upload: mdiUpload,
    continue: mdiMenuDown,
    more: mdiDotsHorizontal,
    loading: mdiDotsCircle,
    play: mdiPlay,
    pause: mdiPause,
    restart: mdiRestart,
} satisfies Record<string, string>

export const EXPR_ICONS: Record<ExprType, string> = {
    unset: mdiSquareOutline,
    list: mdiFormatListGroup,
    string: mdiFormatText,
    number: mdiPound,
    integer: mdiPoundBox,
    boolean: mdiFlag,
    story: mdiBookMultipleOutline,
    chapter: mdiBookOpenVariantOutline,
    scene: mdiTextBoxOutline,
    variable: mdiVariable,
    character: mdiAccount,
    portrait: mdiEmoticon,
    backdrop: mdiImageArea,
    song: mdiMusic,
    sound: mdiVolumeHigh,
    macro: mdiScriptText,
    characterVariable: mdiApplicationVariable,
    location: mdiArrowExpandHorizontal,
    add: mdiPlus,
    subtract: mdiMinus,
    multiply: mdiClose,
    divide: mdiSlashForward,
    modulo: mdiPercent,
    round: mdiArrowExpandVertical,
    roundUp: mdiArrowExpandUp,
    roundDown: mdiArrowExpandDown,
    randomFloat: mdiDiceMultiple,
    randomInt: mdiDice3,
    lowerCase: mdiFormatLetterCaseLower,
    upperCase: mdiFormatLetterCaseUpper,
    format: mdiSignatureText,
    equal: mdiEqual,
    notEqual: mdiNotEqualVariant,
    lessThan: mdiLessThan,
    lessThanOrEqual: mdiLessThanOrEqual,
    greaterThan: mdiGreaterThan,
    greaterThanOrEqual: mdiGreaterThanOrEqual,
    pick: mdiFormatListChecks,
    switch: mdiFormatListCheckbox,
}

export const EXPR_VALUE_ICONS: Record<ExprPrimitiveValueType, string> = {
    string: EXPR_ICONS['string'],
    number: EXPR_ICONS['number'],
    boolean: EXPR_ICONS['boolean'],
    integer: EXPR_ICONS['integer'],
    story: EXPR_ICONS['story'],
    chapter: EXPR_ICONS['chapter'],
    scene: EXPR_ICONS['scene'],
    variable: EXPR_ICONS['variable'],
    character: EXPR_ICONS['character'],
    portrait: EXPR_ICONS['portrait'],
    backdrop: EXPR_ICONS['backdrop'],
    song: EXPR_ICONS['song'],
    sound: EXPR_ICONS['sound'],
    location: EXPR_ICONS['location'],
    macro: EXPR_ICONS['macro'],
}

export const PROJECT_TAB_ICONS: Record<ProjectEditorTab, string> = {
    home: mdiHome,
    manual: mdiMapSearch,
    settings: mdiCog,
    project: mdiArchive,
    stories: EXPR_ICONS['story'],
    chapters: EXPR_ICONS['chapter'],
    scenes: EXPR_ICONS['scene'],
    characters: EXPR_ICONS['character'],
    portraits: EXPR_ICONS['portrait'],
    backdrops: EXPR_ICONS['backdrop'],
    songs: EXPR_ICONS['song'],
    sounds: EXPR_ICONS['sound'],
    variables: EXPR_ICONS['variable'],
    macros: EXPR_ICONS['macro'],
}

export const STEP_ICONS: Record<StepType, string> = {
    text: mdiAccountVoice,
    narrate: mdiText,
    backdrop: EXPR_ICONS['backdrop'],
    enter: mdiAccountPlus,
    exit: mdiAccountMinus,
    move: mdiArrowExpandHorizontal,
    portrait: EXPR_ICONS['portrait'],
    music: EXPR_ICONS['song'],
    sound: EXPR_ICONS['sound'],
    decision: mdiFormatListText,
    branch: mdiSourceBranch,
    prompt: mdiFormTextbox,
    set: mdiApplicationVariable,
    macro: mdiScriptTextPlay,
    returnTo: mdiArrowULeftTop,
    goto: mdiArrowRightBox,
}
